name: shoppy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  firebase_database: ^10.5.7
  font_awesome_flutter: ^10.7.0
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  web_socket_channel: ^3.0.0
  zoom_tap_animation: ^1.1.0
  loader_overlay: ^4.0.1
  lottie: ^3.1.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  get_cli: ^1.6.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

